spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://course-db:5432/course_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

