spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://rating-db:5432/rating_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8081}
  course-service:
    url: ${COURSE_SERVICE_URL:http://course-service:8082}

