spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://user-db:5432/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

